const { isPackageExists } = require('local-pkg')

const withTypescript = isPackageExists('typescript')

if (!withTypescript)
  console.warn('[@byyuurin/eslint-config] TypeScript is not installed, fallback to JS only.')

module.exports = {
  extends: [
    'plugin:vue/vue3-recommended',
    withTypescript
      ? '@byyuurin/eslint-config-typescript'
      : '@byyuurin/eslint-config-basic',
  ],

  plugins: [
    // https://github.com/vuejs/eslint-plugin-vue
    'vue',
  ],

  overrides: [
    {
      files: ['*.vue'],
      parser: 'vue-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
      },
      rules: {
        'no-undef': 'off',
        'unicorn/prefer-top-level-await': 'off',
        'simple-import-sort/imports': ['warn', {
          groups: [
            ['^\\u0000'],
            ['^vue', '^@?\\w', '^', '^\\.'],
          ],
        }],
      },
    },
  ],

  rules: {
    // Essential
    // https://eslint.vuejs.org/rules/#priority-a-essential-error-prevention
    // ----------------------------------------
    'vue/multi-word-component-names': 'off',
    // 'vue/no-arrow-functions-in-watch': 'error',
    // 'vue/no-async-in-computed-properties': 'error',
    // 'vue/no-child-content': 'error',
    // 'vue/no-computed-properties-in-data': 'error',
    // 'vue/no-custom-modifiers-on-v-model': 'error',
    'vue/no-deprecated-data-object-declaration': 'warn',
    'vue/no-deprecated-destroyed-lifecycle': 'warn',
    // 'vue/no-deprecated-dollar-listeners-api': 'error',
    'vue/no-deprecated-dollar-scopedslots-api': 'warn',
    // 'vue/no-deprecated-events-api': 'error',
    // 'vue/no-deprecated-filter': 'error',
    // 'vue/no-deprecated-functional-template': 'error',
    // 'vue/no-deprecated-html-element-is': 'error',
    'vue/no-deprecated-inline-template': 'error',
    // 'vue/no-deprecated-props-default-this': 'error',
    'vue/no-deprecated-router-link-tag-prop': 'error',
    'vue/no-deprecated-scope-attribute': 'warn',
    'vue/no-deprecated-slot-attribute': 'warn',
    'vue/no-deprecated-slot-scope-attribute': 'warn',
    // 'vue/no-deprecated-v-bind-sync': 'warn',
    // 'vue/no-deprecated-v-is': 'warn',
    // 'vue/no-deprecated-v-on-native-modifier': 'error',
    'vue/no-deprecated-v-on-number-modifiers': 'warn',
    // 'vue/no-deprecated-vue-config-keycodes': 'error',
    // 'vue/no-dupe-keys': 'error',
    // 'vue/no-dupe-v-else-if': 'error',
    // 'vue/no-duplicate-attributes': 'error',
    // 'vue/no-export-in-script-setup': 'error',
    // 'vue/no-expose-after-await': 'error',
    // 'vue/no-lifecycle-after-await': 'error',
    // 'vue/no-multiple-template-root': 'error',
    // 'vue/no-mutating-props': 'error',
    // 'vue/no-parsing-error': 'error',
    'vue/no-ref-as-operand': 'warn',
    // 'vue/no-reserved-component-names': 'error',
    // 'vue/no-reserved-keys': 'error',
    // 'vue/no-reserved-props': 'error',
    // 'vue/no-setup-props-destructure': 'error',
    'vue/no-shared-component-data': 'warn',
    // 'vue/no-side-effects-in-computed-properties': 'error',
    // 'vue/no-template-key': 'error',
    // 'vue/no-textarea-mustache': 'error',
    // 'vue/no-unused-components': 'error',
    // 'vue/no-unused-vars': 'error',
    // 'vue/no-use-computed-property-like-method': 'error',
    // 'vue/no-use-v-if-with-v-for': 'error',
    // 'vue/no-useless-template-attributes': 'error',
    // 'vue/no-v-for-template-key-on-child': 'error',
    // 'vue/no-v-for-template-key': 'error',
    // 'vue/no-v-model-argument': 'error',
    'vue/no-v-text-v-html-on-component': 'error',
    // 'vue/no-watch-after-await': 'error',
    'vue/prefer-import-from-vue': 'warn',
    // 'vue/require-component-is': 'error',
    'vue/require-prop-type-constructor': 'warn',
    // 'vue/require-render-return': 'error',
    // 'vue/require-slots-as-functions': 'error',
    // 'vue/require-toggle-inside-transition': 'error',
    // 'vue/require-v-for-key': 'error',
    // 'vue/require-valid-default-prop': 'error',
    // 'vue/return-in-computed-property': 'error',
    // 'vue/return-in-emits-validator': 'error',
    // 'vue/use-v-on-exact': 'error',
    // 'vue/valid-attribute-name': 'error',
    // 'vue/valid-define-emits': 'error',
    // 'vue/valid-define-props': 'error',
    // 'vue/valid-model-definition': 'error',
    // 'vue/valid-next-tick': 'warn',
    // 'vue/valid-template-root': 'error',
    // 'vue/valid-v-bind-sync': 'error',
    // 'vue/valid-v-bind': 'error',
    // 'vue/valid-v-cloak': 'error',
    // 'vue/valid-v-else-if': 'error',
    // 'vue/valid-v-else': 'error',
    // 'vue/valid-v-for': 'error',
    // 'vue/valid-v-html': 'error',
    // 'vue/valid-v-if': 'error',
    // 'vue/valid-v-is': 'error',
    // 'vue/valid-v-memo': 'error',
    // 'vue/valid-v-model': 'error',
    // 'vue/valid-v-on': 'error',
    // 'vue/valid-v-once': 'error',
    // 'vue/valid-v-pre': 'error',
    // 'vue/valid-v-show': 'error',
    // 'vue/valid-v-slot': 'error',
    // 'vue/valid-v-text': 'error',

    // Strongly Recommended
    // https://eslint.vuejs.org/rules/#priority-b-strongly-recommended-improving-readability
    // ----------------------------------------
    'vue/attribute-hyphenation': 'warn',
    'vue/component-definition-name-casing': 'warn',
    'vue/first-attribute-linebreak': 'warn',
    'vue/html-closing-bracket-newline': 'warn',
    'vue/html-closing-bracket-spacing': 'warn',
    'vue/html-end-tags': 'warn',
    'vue/html-indent': 'warn',
    'vue/html-quotes': 'warn',
    'vue/html-self-closing': [
      'warn',
      {
        html: {
          void: 'always',
          normal: 'never',
          component: 'always',
        },
        svg: 'always',
        math: 'always',
      },
    ],
    'vue/max-attributes-per-line': 'off',
    'vue/multiline-html-element-content-newline': 'warn',
    'vue/mustache-interpolation-spacing': 'warn',
    'vue/no-multi-spaces': 'warn',
    'vue/no-spaces-around-equal-signs-in-attribute': 'warn',
    // 'vue/no-template-shadow': 'error',
    // 'vue/one-component-per-file': 'error',
    // 'vue/prop-name-casing': 'error',
    'vue/require-default-prop': 'off',
    // 'vue/require-explicit-emits': 'error',
    'vue/require-prop-types': 'off',
    'vue/singleline-html-element-content-newline': 'warn',
    'vue/v-bind-style': 'warn',
    'vue/v-on-event-hyphenation': ['warn', 'always', { autofix: true }],
    'vue/v-on-style': 'warn',
    'vue/v-slot-style': 'warn',

    // Recommended
    // https://eslint.vuejs.org/rules/#priority-c-recommended-potentially-dangerous-patterns
    // ----------------------------------------
    'vue/attributes-order': 'warn',
    'vue/component-tags-order': [
      'warn',
      { order: ['script', 'template', 'style'] },
    ],
    // 'vue/no-lone-template': 'error',
    // 'vue/no-multiple-slot-args': 'error',
    'vue/no-v-html': 'off',
    'vue/order-in-components': 'warn',
    'vue/this-in-template': 'warn',

    // Uncategorized
    // https://eslint.vuejs.org/rules/#uncategorized
    // ----------------------------------------
    // 'vue/block-lang': 'error',
    'vue/block-tag-newline': [
      'warn',
      { singleline: 'always', multiline: 'always' },
    ],
    // 'vue/component-api-style': 'error',
    'vue/component-name-in-template-casing': [
      'warn', 'PascalCase', {
        registeredComponentsOnly: false,
        ignores: [],
      },
    ],
    'vue/component-options-name-casing': ['warn', 'PascalCase'],
    'vue/custom-event-name-casing': [
      'error', 'kebab-case',
      { ignores: [] },
    ],
    // 'vue/define-emits-declaration': 'error',
    'vue/define-macros-order': 'warn',
    // 'vue/define-props-declaration': 'error',
    // 'vue/html-button-has-type': 'error',
    'vue/html-comment-content-newline': [
      'warn',
      { singleline: 'never', multiline: 'ignore' },
    ],
    'vue/html-comment-content-spacing': [
      'warn', 'always',
      { exceptions: [] },
    ],
    // 'vue/html-comment-indent': 'warn',
    // 'vue/match-component-file-name': 'error',
    // 'vue/match-component-import-name': 'error',
    // 'vue/max-lines-per-block': 'error',
    // 'vue/new-line-between-multi-line-property': 'warn',
    // 'vue/next-tick-style': 'error',
    // 'vue/no-bare-strings-in-template': 'error',
    // 'vue/no-boolean-default': 'error',
    // 'vue/no-duplicate-attr-inheritance': 'error',
    // 'vue/no-empty-component-block': 'error',
    // 'vue/no-multiple-objects-in-class': 'error',
    // 'vue/no-potential-component-option-typo': 'error',
    // 'vue/no-ref-object-destructure': 'error',
    // 'vue/no-required-prop-with-default': 'warn',
    // 'vue/no-restricted-block': 'error',
    // 'vue/no-restricted-call-after-await': 'error',
    // 'vue/no-restricted-class': 'error',
    // 'vue/no-restricted-component-names': 'error',
    // 'vue/no-restricted-component-options': 'error',
    // 'vue/no-restricted-custom-event': 'error',
    // 'vue/no-restricted-html-elements': 'error',
    // 'vue/no-restricted-props': 'error',
    // 'vue/no-restricted-static-attribute': 'error',
    'vue/no-restricted-v-bind': ['error', '/^v-/'],
    // 'vue/no-root-v-if': 'error',
    // 'vue/no-static-inline-styles': 'error',
    // 'vue/no-template-target-blank': 'error',
    // 'vue/no-this-in-before-route-enter': 'error',
    // 'vue/no-undef-components': 'error',
    // 'vue/no-undef-properties': 'error',
    // 'vue/no-unsupported-features': ['error', { version: '^3.3.0', ignores: [] }],
    // 'vue/no-unused-properties': 'error',
    'vue/no-unused-refs': 'error',
    // 'vue/no-use-v-else-with-v-for': 'error',
    'vue/no-useless-mustaches': 'warn',
    'vue/no-useless-v-bind': 'warn',
    // 'vue/no-v-text': 'error',
    'vue/padding-line-between-blocks': ['warn', 'always'],
    'vue/padding-line-between-tags': ['warn', [{ blankLine: 'never', prev: '*', next: '*' }]],
    // 'vue/padding-lines-in-component-definition': 'warn',
    // 'vue/prefer-define-options': 'warn',
    // 'vue/prefer-prop-type-boolean-first': 'error',
    'vue/prefer-separate-static-class': 'warn',
    // 'vue/prefer-true-attribute-shorthand': 'error',
    // 'vue/require-direct-export': 'error',
    // 'vue/require-emit-validator': 'error',
    // 'vue/require-expose': 'error',
    // 'vue/require-macro-variable-name': 'error',
    // 'vue/require-name-property': 'error',
    // 'vue/require-prop-comment': 'error',
    // 'vue/require-typed-object-prop': 'error',
    // 'vue/require-typed-ref': 'error',
    // 'vue/script-indent': ['warn', 2, { baseIndent: 0, switchCase: 0, ignores: [] }],
    // 'vue/sort-keys': 'error',
    // 'vue/static-class-names-order': 'warn',
    // 'vue/v-for-delimiter-style': ['warn', 'in'],
    // 'vue/v-on-handler-style': ['warn', ['method', 'inline-function'], { ignoreIncludesComment: false }],
    // 'vue/valid-define-options': 'error',

    // Extension Rules
    // https://eslint.vuejs.org/rules/#extension-rules
    // ----------------------------------------
    'vue/array-bracket-newline': ['warn', { multiline: true }],
    'vue/array-bracket-spacing': ['warn', 'never'],
    // 'vue/array-element-newline': 'warn',
    'vue/arrow-spacing': ['warn', { before: true, after: true }],
    'vue/block-spacing': ['warn', 'always'],
    'vue/brace-style': ['warn', 'stroustrup', { allowSingleLine: false }],
    'vue/camelcase': 'off',
    'vue/comma-dangle': ['warn', 'always-multiline'],
    'vue/comma-spacing': ['warn', { before: false, after: true }],
    'vue/comma-style': ['warn', 'last'],
    'vue/dot-location': ['warn', 'property'],
    'vue/dot-notation': ['warn', { allowKeywords: true }],
    'vue/eqeqeq': ['error', 'smart'],
    'vue/func-call-spacing': ['warn', 'never'],
    'vue/key-spacing': ['warn', { beforeColon: false, afterColon: true }],
    'vue/keyword-spacing': ['warn', { before: true, after: true }],
    'vue/max-len': 'off',
    // 'vue/multiline-ternary': 'warn',
    // 'vue/no-console': 'error',
    'vue/no-constant-condition': ['error', { checkLoops: false }],
    'vue/no-empty-pattern': 'error',
    'vue/no-extra-parens': ['warn', 'functions'],
    'vue/no-irregular-whitespace': 'error',
    'vue/no-loss-of-precision': 'error',
    'vue/no-restricted-syntax': ['error', 'DebuggerStatement', 'LabeledStatement', 'WithStatement'],
    'vue/no-sparse-arrays': 'error',
    'vue/no-useless-concat': 'error',
    'vue/object-curly-newline': ['warn', { multiline: true, consistent: true }],
    'vue/object-curly-spacing': ['warn', 'always'],
    'vue/object-property-newline': ['warn', { allowMultiplePropertiesPerLine: true }],
    'vue/object-shorthand': ['warn', 'always', { ignoreConstructors: false, avoidQuotes: true }],
    'vue/operator-linebreak': ['warn', 'before'],
    'vue/prefer-template': 'warn',
    'vue/quote-props': ['warn', 'consistent-as-needed'],
    'vue/space-in-parens': ['warn', 'never'],
    'vue/space-infix-ops': 'warn',
    'vue/space-unary-ops': ['warn', { words: true, nonwords: false }],
    'vue/template-curly-spacing': ['warn', 'never'],
  },
}
