module.exports = {
  plugins: [
    // https://github.com/eslint/eslint-plugin-markdown
    'markdown',
    // https://github.com/BenoitZugmeyer/eslint-plugin-html
    'html',
    // https://github.com/antfu/eslint-config/tree/main/packages/eslint-plugin-antfu
    'antfu',
  ],
  settings: {
    html: {
      'report-bad-indent': 'warn',
    },
  },
  extends: [
    'plugin:markdown/recommended',
  ],
  rules: {
    // https://eslint.org/docs/latest/rules/#possible-problems
    // ----------------------------------------
    'array-callback-return': 'error',
    'constructor-super': 'error',
    'for-direction': 'error',
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': ['error', 'always'],
    'no-const-assign': 'error',
    'no-constant-condition': ['error', { checkLoops: false }],
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-ex-assign': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-import-assign': 'error',
    'no-inner-declarations': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-new-symbol': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-self-assign': ['error', { props: true }],
    'no-self-compare': 'error',
    'no-setter-return': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-this-before-super': 'error',
    'no-undef': 'error',
    'no-unexpected-multiline': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unreachable': 'error',
    'no-unreachable-loop': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-use-before-define': [
      'error', {
        functions: false,
        classes: false,
        variables: true,
      },
    ],
    'no-useless-backreference': 'error',
    'use-isnan': [
      'error',
      {
        enforceForSwitchCase: true,
        enforceForIndexOf: true,
      },
    ],
    'valid-typeof': ['error', { requireStringLiterals: true }],

    // https://eslint.org/docs/latest/rules/#suggestions
    // ----------------------------------------
    'accessor-pairs': [
      'error',
      {
        setWithoutGet: true,
        getWithoutSet: false,
        enforceForClassMembers: true,
      },
    ],
    'arrow-body-style': ['warn', 'as-needed'],
    'block-scoped-var': 'error',
    // 'camelcase': 'off',
    // 'capitalized-comments': 'off',
    'curly': ['warn', 'multi-or-nest', 'consistent'],
    'default-case-last': 'error',
    'dot-notation': ['warn', { allowKeywords: true }],
    'eqeqeq': ['warn', 'smart'],
    'logical-assignment-operators': ['warn', 'always'],
    // 'multiline-comment-style': ['warn', 'separate-lines'],
    'new-cap': ['error', { newIsCap: true, capIsNew: false, properties: true }],
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-confusing-arrow': 'warn',
    'no-console': ['error', { allow: ['warn', 'error'] }],
    'no-delete-var': 'error',
    'no-else-return': 'warn',
    'no-empty': ['error', { allowEmptyCatch: true }],
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'warn',
    'no-extra-boolean-cast': 'warn',
    'no-extra-label': 'warn',
    'no-extra-semi': 'warn',
    'no-floating-decimal': 'warn',
    'no-global-assign': 'error',
    'no-implicit-coercion': ['error', { allow: ['!!'] }],
    'no-implied-eval': 'error',
    'no-iterator': 'error',
    'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
    'no-lone-blocks': 'error',
    'no-lonely-if': 'warn',
    'no-mixed-operators': [
      'error',
      {
        groups: [
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||', '?:'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: true,
      },
    ],
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-object': 'error',
    'no-new-wrappers': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-proto': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'warn',
    'no-restricted-syntax': ['error', 'DebuggerStatement', 'LabeledStatement', 'WithStatement'],
    'no-return-assign': 'error',
    'no-return-await': 'error',
    'no-sequences': 'error',
    'no-shadow-restricted-names': 'error',
    'no-throw-literal': 'error',
    'no-undef-init': 'warn',
    'no-unneeded-ternary': ['warn', { defaultAssignment: false }],
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTernary: true,
        allowTaggedTemplates: true,
      },
    ],
    'no-unused-labels': 'warn',
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-computed-key': 'warn',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-escape': 'error',
    'no-useless-rename': 'warn',
    'no-useless-return': 'warn',
    'no-var': 'warn',
    'no-void': 'error',
    'no-with': 'error',
    'object-shorthand': [
      'warn', 'always',
      {
        ignoreConstructors: false,
        avoidQuotes: true,
      },
    ],
    'one-var': ['warn', { initialized: 'never' }],
    'operator-assignment': ['warn', 'always'],
    'prefer-arrow-callback': [
      'warn',
      {
        allowNamedFunctions: false,
        allowUnboundThis: true,
      },
    ],
    'prefer-const': [
      'warn',
      {
        destructuring: 'all',
        ignoreReadBeforeAssign: true,
      },
    ],
    'prefer-exponentiation-operator': 'warn',
    'prefer-numeric-literals': 'warn',
    'prefer-object-has-own': 'warn',
    'prefer-object-spread': 'warn',
    'prefer-promise-reject-errors': 'error',
    'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'warn',
    'quote-props': ['warn', 'consistent-as-needed'],
    'require-await': 'error',
    'require-yield': 'error',
    'sort-vars': 'warn',
    'spaced-comment': [
      'warn', 'always',
      {
        line: {
          markers: ['/'],
          exceptions: ['/', '#'],
        },
        block: {
          markers: ['!'],
          exceptions: ['*'],
          balanced: true,
        },
      },
    ],
    'strict': 'warn',
    'symbol-description': 'error',
    'vars-on-top': 'error',
    'yoda': ['warn', 'never'],

    // https://eslint.org/docs/latest/rules/#layout--formatting
    // ----------------------------------------
    'array-bracket-newline': ['warn', 'consistent'],
    'array-bracket-spacing': ['warn', 'never'],
    'arrow-parens': ['warn', 'always'],
    'arrow-spacing': ['warn', { before: true, after: true }],
    'block-spacing': ['warn', 'always'],
    'brace-style': ['warn', 'stroustrup', { allowSingleLine: false }],
    'comma-dangle': ['warn', 'always-multiline'],
    'comma-spacing': ['warn', { before: false, after: true }],
    'comma-style': ['warn', 'last'],
    'computed-property-spacing': ['warn', 'never', { enforceForClassMembers: true }],
    'dot-location': ['warn', 'property'],
    'eol-last': ['warn', 'always'],
    'func-call-spacing': ['warn', 'never'],
    'function-paren-newline': ['warn', 'consistent'],
    'generator-star-spacing': ['warn', { before: false, after: true }],
    'indent': [
      'warn', 2,
      {
        SwitchCase: 1,
        VariableDeclarator: 1,
        outerIIFEBody: 1,
      },
    ],
    'key-spacing': ['warn', { beforeColon: false, afterColon: true }],
    'keyword-spacing': ['warn', { before: true, after: true }],
    // 'linebreak-style': 'off',
    'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
    'max-statements-per-line': ['error', { max: 1 }],
    'multiline-ternary': ['warn', 'always-multiline'],
    'new-parens': 'warn',
    'no-extra-parens': ['warn', 'functions'],
    'no-mixed-spaces-and-tabs': 'error',
    'no-multi-spaces': 'warn',
    'no-multiple-empty-lines': ['warn', { max: 1, maxBOF: 0, maxEOF: 0 }],
    'no-tabs': 'error',
    'no-trailing-spaces': [
      'warn',
      {
        skipBlankLines: false,
        ignoreComments: false,
      },
    ],
    'no-whitespace-before-property': 'warn',
    'object-curly-newline': ['warn', { multiline: true, consistent: true }],
    'object-curly-spacing': ['warn', 'always'],
    'object-property-newline': ['warn', { allowMultiplePropertiesPerLine: true }],
    'operator-linebreak': ['warn', 'before'],
    'padded-blocks': [
      'warn',
      {
        blocks: 'never',
        switches: 'never',
        classes: 'never',
      },
    ],
    'padding-line-between-statements': [
      'warn',
      { blankLine: 'always', prev: 'block-like', next: '*' },
      { blankLine: 'always', prev: '*', next: 'block-like' },
      { blankLine: 'always', prev: 'if', next: '*' },
      { blankLine: 'always', prev: '*', next: 'if' },
    ],
    'quotes': ['warn', 'single'],
    'rest-spread-spacing': ['warn', 'never'],
    'semi': ['warn', 'never'],
    'semi-spacing': ['warn', { before: false, after: true }],
    'space-before-blocks': ['warn', 'always'],
    'space-before-function-paren': [
      'warn',
      {
        anonymous: 'always',
        named: 'never',
        asyncArrow: 'always',
      },
    ],
    'space-in-parens': ['warn', 'never'],
    'space-infix-ops': 'warn',
    'space-unary-ops': ['warn', { words: true, nonwords: false }],
    'template-curly-spacing': ['warn', 'never'],
    'template-tag-spacing': ['warn', 'never'],
    'unicode-bom': ['warn', 'never'],
    'wrap-iife': ['warn', 'any', { functionPrototypeMethods: true }],
    'yield-star-spacing': ['warn', 'both'],

    // https://eslint.org/docs/latest/rules/#deprecated
    // ----------------------------------------

    // https://eslint.org/docs/latest/rules/#removed
    // ----------------------------------------

    // EditorConfig
    // ----------------------------------------
    // indent, eol-last, linebreak-style, no-trailing-spaces

    // antfu
    // ----------------------------------------
    'antfu/if-newline': 'warn',
    'antfu/import-dedupe': 'warn',
  },
}
